<a href="https://colab.research.google.com/github/couqdev/MachineLearning/blob/main/Lab_3_20130376_TranDangQuoc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Deadline: 23:59, 04/03/2023**

# Task 1. 
The main aim of this task is to get familiar with the tasks of preprocessing data using Scikit-learn â€“ a Python-based Machine Learning framework and Linear Regression.

For given 2 datasets (preprocessing_weather.csv, preprocessing_salary_dummy.csv), 
*   Identify issues with these datasets
*   Then, apply preprocessing techniques to the datasets

#Task 1.1. Dataset preprocessing_weather.csv

**Issues**:


1.   List item
2.   List item
3.   List item
4.   List item
....

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')
%cd '/content/gdrive/MyDrive/MachineLeaning'

Mounted at /content/gdrive
/content/gdrive/MyDrive/MachineLeaning

In [69]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

**Preprocessing dataset**:

In [14]:
#code
dataset1 = pd.read_csv("preprocessing_weather.csv")
imputer = SimpleImputer(missing_values=np.NaN, strategy='median')
# X = dataset1.iloc[:,2:4].values
# imputer.fit_transform(X)
dataset1['temperature'] = imputer.fit_transform(dataset1['temperature'].values.reshape(-1, 1))
dataset1['humidity'] = imputer.fit_transform(dataset1['humidity'].values.reshape(-1, 1))
dataset1

    id   outlook  temperature  humidity  windy play
0    1     sunny         85.0      85.0  False   no
1    2     sunny         80.0      90.0   True   no
2    3  overcast         83.0      86.0  False  yes
3    4     rainy         72.0      96.0  False  yes
4    5     rainy         68.0      80.0  False  yes
5    6     rainy         65.0      70.0   True   no
6    7  overcast         64.0      65.0   True  yes
7    8     sunny         72.0      95.0  False   no
8    9     sunny         69.0      85.0  False  yes
9   10     rainy         75.0      80.0  False  yes
10  11     sunny         75.0      70.0   True  yes
11  12  overcast         72.0      90.0   True  yes
12  13  overcast         81.0      75.0  False  yes
13  14     rainy         71.0      91.0   True   no

#Task 1.2. Dataset preprocessing_salary_dummy.csv

**Issues**:


1.   List item
2.   List item
3.   List item
4.   List item
....

**Preprocessing dataset**:

In [56]:
#code
dataset2 = pd.read_csv("preprocessing_salary_dummy.csv")
imputer2 = SimpleImputer(missing_values=np.NaN, strategy='median')
# # X = dataset2.iloc[:,2:4].values
# # imputer2.fit_transform(X)
dataset2[' Age'] = imputer2.fit_transform(dataset2[' Age'].values.reshape(-1,1))
dataset2['   Salary '] = imputer2.fit_transform(dataset2['   Salary '].values.reshape(-1, 1))
dataset2

   No    Country   Age     Salary  Purchased
0   1     France  44.0     72000.0        No
1   2      Spain  27.0     48000.0       Yes
2   3    Germany  30.0     54000.0        No
3   4      Spain  38.0     61000.0        No
4   5    Germany  40.0     61000.0       Yes
5   6     France  35.0     58000.0       Yes
6   7      Spain  38.0     52000.0        No
7   8     France  48.0     79000.0       Yes
8   9    Germany  50.0     83000.0        No
9  10     France  37.0     67000.0       Yes

# **Task 2**. Simple Linear Regression in Scikit-Learn
---
# **Usage:**
> **Step 1**: build a model
![image.png]()

> **Step 2**: test the model

*   With test set:
`y_pred = regressor.predict(X_test)`

*   With a single value ("predict" method always expects a 2D array as the format of its inputs)
`regressor.predict([[12]])`

> **Step 3**: 
*   get w0, w1 , w2, â€¦,
-- W0: `regressor.intercept_`
-- w1, w2, â€¦: `regressor.coef_`
*   R^2 score: sum of squared r(i)
`r(i) = y(i) - f(x(i))`: residual of ith instance


> **Metrics**:
*   metrics.explained_variance_score(y_test, y_pred)
*   metrics.mean_absolute_error(y_ test, y_pred) 
*   metrics.mean_squared_error(y_ test, y_pred[, ...])
*   metrics.mean_squared_log_error(y_ test, y_pred)
*   metrics.median_absolute_error(y_ test, y_pred)
*   metrics.r2_score(y_ test, y_pred[, ...])



---

# Tasks
The main aim of these tasks is to get familiar with Linear Regression problems. Apply LinearRegression to the following datasets. Note the error obtained and coefficients
*   **dataset1.csv** - a synthetic dataset including 5 points (1-dimensional data) with one target
*   **dataset2.csv** - a synthetic dataset including 1000 points (3-dimensional data) with one target variable. The variables are named x1, x2, x3, y. y is the variable to be regressed. Split the dataset into training set and test set (70% for training set and 30% for test set).

# Task 2.1. dataset1.csv

In [64]:
#code
data1 = pd.read_csv("dataset1.csv")

X_train = data1[['x']]
y_train = data1[['y']]

regressor = LinearRegression()

regressor.fit(X_train, y_train)

print(regressor.intercept_)
print("------------------------")
print(regressor.coef_)
print("------------------------")
y_pred = regressor.predict(X_train)
print(y_pred)
print("------------------------")
r2 = metrics.r2_score(y_train, y_pred)
print(r2)

[0.4]
------------------------
[[0.8]]
------------------------
[[1.2]
 [2. ]
 [3.6]
 [2.8]
 [4.4]]
------------------------
0.7272727272727273

# Task 2.2. dataset2.csv

In [110]:
#code
data2 = pd.read_csv("dataset2.csv")

X = data2[['x1','x2','x3']]
y = data2[['y']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

regressor = LinearRegression()

regressor.fit(X_train, y_train)

print(regressor.intercept_)
print("------------------------")
print(regressor.coef_)
print("------------------------")
y_pred = regressor.predict(X_train)
print(y_pred)
print("------------------------")
r2 = metrics.r2_score(y_train, y_pred)
print(r2)

[4.00002045]
------------------------
[[2.99999593 3.99999565 4.99999157]]
------------------------
[[-6.76784491e+00]
 [ 3.44856302e+00]
 [-6.16316756e+00]
 [-6.82171836e+00]
 [-1.56468042e+01]
 [ 1.35161281e+01]
 [ 7.67143692e+00]
 [-2.40507572e+00]
 [ 5.36431910e+00]
 [-4.85346722e+00]
 [-1.32011811e+01]
 [ 4.31525371e+00]
 [ 4.57064752e+00]
 [ 1.02676913e+01]
 [ 1.22194444e+01]
 [ 7.42820781e+00]
 [-7.28432152e+00]
 [-6.73674273e+00]
 [ 3.81041536e+00]
 [ 4.13721837e+00]
 [ 3.22156759e+00]
 [ 1.43284777e+00]
 [-1.75846666e+00]
 [ 5.55149839e+00]
 [ 1.68911705e+01]
 [ 5.01573386e+00]
 [ 3.58559975e+00]
 [ 5.05492885e+00]
 [ 2.03432977e+01]
 [-7.82071301e-01]
 [-9.45976123e+00]
 [ 1.20953222e+01]
 [-6.80541474e+00]
 [ 7.43855450e-01]
 [ 4.38892411e+00]
 [ 2.37302556e+00]
 [ 2.42520615e+01]
 [ 1.32966072e+01]
 [ 1.34147065e+01]
 [ 1.99904494e+01]
 [ 4.06807775e+00]
 [ 8.01559726e+00]
 [ 3.67055156e+00]
 [ 1.04785079e+01]
 [ 6.05060606e+00]
 [ 9.34437437e+00]
 [-5.43100272e+00]
 [-1.44970552e+01]
 [ 1.20380886e+01]
 [ 4.90871400e+00]
 [ 1.65468108e+01]
 [ 1.15047572e+01]
 [ 1.33818070e+01]
 [-8.22956080e+00]
 [ 1.93218870e+01]
 [ 1.54004218e+00]
 [ 3.57866316e+00]
 [ 9.16851506e+00]
 [-8.51520215e+00]
 [ 1.67994402e+01]
 [ 2.98557841e+01]
 [-4.12457040e+00]
 [ 8.92927478e-01]
 [-1.40031560e+01]
 [-7.17387127e+00]
 [ 1.44104976e+01]
 [-3.99527875e+00]
 [-2.96895481e+00]
 [ 2.08644545e+00]
 [ 1.48799331e+01]
 [ 1.50075866e+01]
 [ 2.07461970e+01]
 [-4.54582353e+00]
 [-3.55768576e+00]
 [-3.40479071e+00]
 [ 4.83820143e+00]
 [ 1.89674383e+01]
 [-1.00550559e+01]
 [-9.67174680e-01]
 [ 7.78645662e+00]
 [-6.70365523e+00]
 [ 2.03910974e+01]
 [-4.20006909e+00]
 [-1.07783359e+01]
 [-5.56532421e+00]
 [-4.14302103e+00]
 [-1.52075253e+00]
 [-9.04021760e+00]
 [ 1.29165046e+01]
 [ 9.32121405e+00]
 [-2.35877002e+00]
 [-7.08756850e+00]
 [-5.41476641e+00]
 [ 3.40821176e+00]
 [ 2.68121759e+00]
 [ 1.38439740e+01]
 [ 5.63486855e+00]
 [ 2.15187997e+00]
 [ 1.89910006e+01]
 [ 6.17936785e+00]
 [-3.76920909e+00]
 [ 2.02985966e+01]
 [ 1.09214115e+01]
 [ 9.56612154e+00]
 [ 7.21222330e-01]
 [ 5.21642407e+00]
 [-4.33705030e-01]
 [ 5.92652745e+00]
 [ 3.85736247e+00]
 [ 7.00500837e+00]
 [-1.07203852e+01]
 [-3.00437020e+00]
 [ 4.68204351e+00]
 [-1.15159575e+01]
 [ 9.63450857e+00]
 [ 1.42105036e+01]
 [-7.83243432e+00]
 [ 2.80402865e+01]
 [ 1.78439012e+01]
 [-8.45857529e-01]
 [-9.22631817e+00]
 [ 9.32576993e+00]
 [-1.72040096e+01]
 [ 7.08245927e+00]
 [ 4.67887933e+00]
 [ 8.54731936e+00]
 [-4.21156737e+00]
 [ 6.73096066e+00]
 [ 2.43318286e+00]
 [-1.44697114e+01]
 [ 1.68486340e+01]
 [-6.43570094e+00]
 [ 1.32947981e+01]
 [-2.21605420e+01]
 [-4.10794635e+00]
 [ 1.61763546e+01]
 [-6.40411671e+00]
 [-1.76718503e+01]
 [ 8.50922239e+00]
 [-1.56826528e+01]
 [ 9.07880736e+00]
 [ 6.73352111e+00]
 [-4.40083069e+00]
 [ 5.15608099e+00]
 [-9.26613827e+00]
 [ 3.88102083e+00]
 [ 4.79470441e+00]
 [ 5.20823753e-01]
 [ 1.60528038e+01]
 [ 9.01623002e+00]
 [-1.42862392e+00]
 [-1.36709853e+01]
 [-1.45689535e+01]
 [-5.33692040e+00]
 [ 5.68656054e-03]
 [ 1.42672663e+01]
 [ 6.66302089e+00]
 [ 1.28334766e+01]
 [-4.55598449e+00]
 [-1.05180357e+01]
 [ 1.27305798e+01]
 [-1.78966779e+00]
 [ 9.82844945e-01]
 [-7.71428053e+00]
 [ 7.69835924e+00]
 [ 3.21813842e+00]
 [-1.86275390e+00]
 [-1.26006650e+00]
 [ 5.52525778e-01]
 [ 1.65342031e+01]
 [ 1.97142356e+00]
 [ 1.16694203e+01]
 [ 1.29672244e+01]
 [ 1.09753768e+01]
 [ 9.64725020e+00]
 [ 8.11594698e+00]
 [ 9.07814412e-01]
 [ 1.68745810e+01]
 [-3.49867934e+00]
 [ 2.73129875e+01]
 [ 1.51606411e+01]
 [ 1.54276834e+00]
 [ 5.11223008e-02]
 [-6.87218285e+00]
 [ 2.08243971e+01]
 [-1.10701567e+01]
 [ 1.31175332e+01]
 [ 1.71459222e+01]
 [-6.35820241e+00]
 [ 2.98494838e+01]
 [-8.48430241e-02]
 [ 1.57402046e+01]
 [-1.21514353e+01]
 [-1.75936287e+00]
 [ 8.78774842e+00]
 [ 7.15929367e-01]
 [ 9.70025980e+00]
 [ 4.97656920e+00]
 [-6.08146602e+00]
 [ 1.10492107e+01]
 [-3.24468779e+00]
 [ 7.28333502e-01]
 [ 2.13863145e+01]
 [-1.56532121e+00]
 [ 7.79421020e+00]
 [ 8.93855929e+00]
 [ 2.14420534e+01]
 [ 2.29114422e+00]
 [ 4.05196009e+00]
 [-9.67435367e-01]
 [ 5.46265610e-02]
 [-8.27896043e+00]
 [ 3.23500367e+00]
 [ 9.17204277e+00]
 [-9.69686874e+00]
 [ 2.01383267e+01]
 [ 4.78177712e+00]
 [ 1.77354578e+01]
 [ 1.46437822e+01]
 [ 1.03656868e+01]
 [ 6.86471113e+00]
 [-1.21046788e+00]
 [ 2.27353716e+01]
 [-1.29775952e+01]
 [ 1.70524922e+01]
 [-1.09062607e+01]
 [ 4.85019870e+00]
 [-5.55806956e+00]
 [-8.98878380e-01]
 [ 1.09215150e+01]
 [-1.06907773e+01]
 [-6.94898248e+00]
 [ 5.38678612e+00]
 [ 9.88559055e+00]
 [ 2.78231359e+00]
 [-7.75977216e-01]
 [ 4.28183685e+00]
 [ 1.36993833e+01]
 [ 1.95331789e+00]
 [ 9.80769295e-01]
 [ 4.47421598e-01]
 [ 5.51239316e+00]
 [ 1.89256782e+01]
 [ 1.39179447e+01]
 [-1.56192522e+01]
 [-1.79665590e+01]
 [ 1.26926613e+01]
 [ 8.76923109e+00]
 [-4.89076055e+00]
 [-1.25658945e+01]
 [ 1.20547073e+01]
 [ 1.75802621e+00]
 [-1.60100423e+00]
 [ 9.99311316e+00]
 [ 1.92707068e+01]
 [ 3.53648595e+00]
 [-7.35699093e+00]
 [ 2.52934107e+00]
 [-6.66477545e-01]
 [ 1.05838058e+01]
 [ 6.03973866e+00]
 [ 1.44096022e+01]
 [ 9.61451162e+00]
 [-2.99720853e+00]
 [-2.81473671e+00]
 [ 1.51963076e+01]
 [ 1.38492806e+00]
 [-1.74804077e+01]
 [ 1.05364763e+01]
 [-7.30296811e+00]
 [ 1.76117742e+01]
 [ 1.11430206e+01]
 [-6.35307178e+00]
 [ 6.17752903e+00]
 [ 2.93286851e+01]
 [ 1.40735594e+01]
 [ 1.70155000e+01]
 [ 1.65679398e+01]
 [ 5.22132725e+00]
 [ 1.78614781e+01]
 [-7.87009022e+00]
 [-9.14636021e+00]
 [-4.53482094e+00]
 [ 7.94377282e-01]
 [ 1.65691010e+01]
 [ 1.48690828e+01]
 [ 1.18078335e+01]
 [ 5.67902859e+00]
 [-1.27527658e+00]
 [-3.49578793e+00]
 [-1.49281921e+01]
 [-3.63847179e+00]
 [ 7.36931429e+00]
 [ 1.38809038e+01]
 [ 2.78751884e+00]
 [-8.00632535e+00]
 [ 1.26598099e+01]
 [ 5.56798194e+00]
 [ 5.96097583e+00]
 [-8.14936213e+00]
 [-8.53046286e+00]
 [ 6.94866622e+00]
 [-1.23130736e+01]
 [ 6.07846803e+00]
 [-6.81081847e+00]
 [-9.95421676e+00]
 [-2.41924918e+00]
 [ 1.05360551e+01]
 [-1.93195613e+00]
 [ 1.47065068e+01]
 [ 8.30791569e+00]
 [ 7.17738793e+00]
 [ 5.15317378e+00]
 [ 3.12621758e+00]
 [-2.24570426e+01]
 [ 8.46472057e+00]
 [-1.12407563e+01]
 [ 1.94942960e+01]
 [ 6.64921487e+00]
 [ 8.35841547e+00]
 [-1.08194265e+01]
 [-9.57652770e+00]
 [-9.67816171e+00]
 [ 2.99738930e+00]
 [ 2.24647225e+00]
 [ 7.15682259e+00]
 [ 7.39998823e+00]
 [ 3.61452601e+00]
 [ 3.70903746e+00]
 [-4.78429751e-01]
 [-3.04887462e+00]
 [ 2.25084559e+00]
 [-1.83030776e+00]
 [ 1.83428052e+01]
 [ 5.73230840e+00]
 [ 8.65964919e+00]
 [ 1.25883196e-02]
 [-1.32823066e+01]
 [ 1.26352926e+00]
 [ 1.53527640e+01]
 [ 3.07299733e+00]
 [ 1.66676717e+01]
 [-1.82017493e+01]
 [-1.01589597e+01]
 [ 5.13400667e-01]
 [ 2.87693592e+00]
 [ 6.88099131e+00]
 [-7.82443275e+00]
 [-1.59388499e+01]
 [-8.30723246e+00]
 [ 1.53651537e+01]
 [-7.62761722e+00]
 [-5.17697182e+00]
 [-1.05885839e+01]
 [ 1.61358213e+01]
 [ 6.76902929e+00]
 [ 1.18867371e+01]
 [-4.45444606e+00]
 [ 9.38791287e+00]
 [ 1.07433652e+01]
 [ 8.85531773e+00]
 [-9.77201405e+00]
 [ 9.99960537e+00]
 [-3.96572637e+00]
 [-1.54642531e+01]
 [ 1.51903957e+01]
 [-1.73810500e+01]
 [ 5.20546920e+00]
 [-1.20237563e+01]
 [ 3.38086486e+00]
 [ 1.50865436e+01]
 [ 4.85460187e+00]
 [ 7.80986820e+00]
 [ 1.60238641e+01]
 [ 1.60925035e+01]
 [ 7.51261011e+00]
 [ 8.22015071e+00]
 [ 1.38668838e+01]
 [ 1.21797097e+01]
 [-1.12352674e+01]
 [-1.09221946e+01]
 [ 7.49384278e-01]
 [ 4.39392355e+00]
 [ 4.95269436e+00]
 [ 1.27412031e+01]
 [ 1.79003968e+01]
 [-1.21684183e+01]
 [-9.20796063e+00]
 [ 1.39046642e+00]
 [ 8.53182007e+00]
 [ 1.72740979e+01]
 [ 1.95649674e+01]
 [ 7.45871177e+00]
 [ 1.83001026e+01]
 [ 4.25493812e+00]
 [ 1.14294271e+01]
 [-3.12073956e+00]
 [ 1.90834008e+01]
 [ 1.62023544e+01]
 [ 5.88951456e+00]
 [-1.29381337e+01]
 [ 6.15405233e+00]
 [-6.34756458e+00]
 [ 3.55611492e+00]
 [ 3.50070361e+00]
 [ 8.93081767e+00]
 [-1.48871933e+01]
 [-8.96311443e+00]
 [-1.91123776e+00]
 [-4.98282135e+00]
 [ 9.32609614e+00]
 [ 6.01957775e+00]
 [ 1.24683347e+01]
 [ 9.63147075e+00]
 [ 4.91886042e+00]
 [-7.36668091e-01]
 [ 6.39577853e+00]
 [ 1.34040040e+01]
 [-9.60021766e+00]
 [ 2.10735752e+01]
 [ 1.68446561e+01]
 [ 1.16877947e+01]
 [ 1.54420738e+01]
 [ 1.03283130e+01]
 [ 1.05538686e+00]
 [ 1.11183127e+01]
 [ 1.92805553e+01]
 [-1.16708527e+00]
 [-7.68626111e+00]
 [-3.89617423e+00]
 [ 2.27759936e+01]
 [-1.86792150e-01]
 [ 1.84040391e+01]
 [ 1.73610018e+01]
 [-1.09247572e+01]
 [ 1.17404127e+01]
 [ 3.77697385e+00]
 [ 2.03650978e+01]
 [ 6.69215663e+00]
 [ 4.82050248e-01]
 [ 3.01260436e+00]
 [ 1.12647778e+01]
 [-5.50856639e+00]
 [-1.03757107e+01]
 [ 1.00300790e+00]
 [ 3.09794195e+00]
 [-3.11923497e+00]
 [ 2.31680049e+00]
 [ 1.45617008e+01]
 [ 2.96401848e+01]
 [ 1.05693062e+01]
 [ 1.32171765e+00]
 [ 1.47169549e+01]
 [-1.06672308e+00]
 [ 7.50391259e+00]
 [ 1.06774947e+01]
 [ 3.03051547e+00]
 [ 3.98345561e+00]
 [ 1.55104161e+01]
 [ 1.95959870e+01]
 [ 6.48782299e+00]
 [-5.15630700e+00]
 [ 2.27463940e+01]
 [-5.72136660e+00]
 [-3.43868047e+00]
 [ 1.49599001e+01]
 [-8.14250532e+00]
 [ 9.12491148e+00]
 [ 1.15347731e+01]
 [-5.34868405e+00]
 [-1.59434508e+01]
 [ 2.44905580e+00]
 [-3.61040990e+00]
 [ 2.05870496e+01]
 [ 1.12386644e+01]
 [ 7.50951167e+00]
 [ 3.58416430e+00]
 [-7.89561270e+00]
 [-6.86345172e+00]]
------------------------
0.999999999398945

# Task 2.3. Apply LinearRegression to the following dataset:
*   Red wine quality: https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv . The dataset includes info about the chemical properties of different types of wine and how they relate to overall quality.

In [107]:
#code
dataset = pd.read_csv('Task3_winequality-red.csv', sep=';')



# sc = StandardScaler()
X = dataset[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']]
y = dataset[['quality']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

regressor1 = LinearRegression()

regressor1.fit(X_train, y_train)

print(regressor1.intercept_)
print("------------------------")
print(regressor1.coef_)
print("------------------------")
y_pred = regressor1.predict(X_train)
print(y_pred)
print("------------------------")
r2 = metrics.r2_score(y_train, y_pred)
print(r2)

[40.44622602]
------------------------
[[ 4.79622779e-02 -1.11840142e+00 -2.76227524e-01  2.04756941e-02
  -1.76890728e+00  5.34980397e-03 -3.44870744e-03 -3.67102234e+01
  -3.47701478e-01  9.29729469e-01  2.66278221e-01]]
------------------------
[[5.27091129]
 [5.72219324]
 [6.97194285]
 ...
 [5.4052491 ]
 [5.07120567]
 [6.53188855]]
------------------------
0.3655849921479044

# Task 2.4. Apply LinearRegression to the following dataset:
*   Energy efficiency: https://archive.ics.uci.edu/ml/datasets/Energy+efficiency.

In [108]:
#code
data = pd.read_excel('Task4_ENB2012_data.xlsx')

X = data[['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8']]
y = data[['Y1', 'Y2']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)
regressor1.fit(X_train, y_train)

print(regressor1.intercept_)
print("------------------------")
print(regressor1.coef_)
print("------------------------")
y_pred = regressor1.predict(X_train)
print(y_pred)
print("------------------------")
r2 = metrics.r2_score(y_train, y_pred)
print(r2)

# data

[81.39324369 98.44986971]
------------------------
[[-6.37286002e+01 -8.12517595e+10  8.12517595e+10  1.62503519e+11
   4.26273978e+00  1.18152044e-02  1.97247948e+01  2.46080644e-01]
 [-7.05912105e+01 -1.36127313e+12  1.36127313e+12  2.72254625e+12
   4.28099442e+00  1.88266629e-01  1.46377981e+01  9.15057063e-02]]
------------------------
[[17.4610063  19.49504233]
 [18.31226633 19.27174815]
 [29.94733916 32.48457587]
 ...
 [ 7.81283595 12.23089159]
 [12.43027349 15.4452086 ]
 [ 8.80921602 12.9888727 ]]
------------------------
0.9073279171397681

# Finally,
Save a copy in your Github. Remember renaming the notebook.